### ISSUE TITLE
Match name/logo/type and team logos

### ISSUE THREAD

**Issue by derpierre65** [th3m4ri0/csgolounge-api#1]
Please add the match name/logo/type and team logos to the public api
Heres my version: https://github.com/derpierre65/csgolounge-api/blob/af147c5596305e373a623261e28f3bd9dd0c483f/lounge.js#L41-L55 and it works.

Thanx and nice api :)

**Comment by edorgeville** [comment]
Great idea ! Would you mind making a pull request for your change ? Thanks !

**Comment by derpierre65** [comment]
i dont know if you want to add the timestamp (beginning the match)?
https://github.com/derpierre65/csgolounge-api/blob/master/lounge.js#L52-L73

**Comment by edorgeville** [comment]
Sounds great too !
